services:
  arborea:
    image: arborea
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      VITE_PORT: ${CLIENT_PORT:-5173}
      VITE_SERVER_URL: http://${SERVER_HOST:-server}:${SERVER_PORT:-3000}
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./arborea:/app
      - /app/node_modules